services:
    fimiz_blog_api_server_1:
        container_name: fimiz_blog_api_server_container_1
        image: fimiz/blog:latest
        ports:
            - 1111:6000
        environment:
            - PORT=5000
            - MAIL_PORT=${MAIL_PORT}
            - MAIL_HOST=${MAIL_HOST}
            - MAIL_USER=${MAIL_USER}
            - MAIL_PASS=${MAIL_PASS}
            - PG_DB_PASSWORD=${PG_DB_PASSWORD}
            - PG_DB_USERNAME=${PG_DB_USERNAME}
            - PG_DB_HOST=${PG_DB_HOST}
            - PG_DB_NAME=${PG_DB_NAME}
    fimiz_blog_api_server_2:
        container_name: fimiz_blog_api_server_container_2
        image: fimiz/blog:latest
        ports:
            - 2222:6000
        environment:
            - PORT=5000
              - MAIL_PORT=${MAIL_PORT}
              - MAIL_HOST=${MAIL_HOST}
              - MAIL_USER=${MAIL_USER}
              - MAIL_PASS=${MAIL_PASS}
              - PG_DB_PASSWORD=${PG_DB_PASSWORD}
              - PG_DB_USERNAME=${PG_DB_USERNAME}
              - PG_DB_HOST=${PG_DB_HOST}
              - PG_DB_NAME=${PG_DB_NAME}
    fimiz_blog_api_server_3:
        container_name: fimiz_blog_api_server_container_3
        image: fimiz/blog:latest
        ports:
            - 3333:6000
        environment:
            - PORT=5000
              - MAIL_PORT=${MAIL_PORT}
              - MAIL_HOST=${MAIL_HOST}
              - MAIL_USER=${MAIL_USER}
              - MAIL_PASS=${MAIL_PASS}
              - PG_DB_PASSWORD=${PG_DB_PASSWORD}
              - PG_DB_USERNAME=${PG_DB_USERNAME}
              - PG_DB_HOST=${PG_DB_HOST}
              - PG_DB_NAME=${PG_DB_NAME}
    nginx:
        container_name: nginx_container
        build:
            context: ./nginx/
            dockerfile: Dockerfile
        ports:
            - 6000:80
        depends_on:
            - fimiz_blog_api_server_1
            - fimiz_blog_api_server_2
            - fimiz_blog_api_server_3
