name: Run Servers and Nginx

on: 
    workflow_run:
        workflows: ["CD Pipeline"]
        types: 
           - completed     

jobs:
  deploy-2:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
    
        - name: Set up SSH key
          run: |
            echo "$SSH_PRIVATE_KEY" > private_key
            chmod 400 private_key
    
        - name: Run Servers and Nginx
          run: |
            ssh -o StrictHostKeyChecking=no -i private_key ${REMOTE_USER}@${REMOTE_HOST} << EOF
              echo "Connected to ec2 successfully"
              cd home
              ls -la 
              echo "GIVING EXEC PERMISSION TO fimiz.sh"
              sudo chmod +x fimiz.sh
              echo "SETTING ENVS WITH FIMIZ FILE"
              ./fimiz.sh
            EOF
    
            echo "LOGIN TO DOCKERHUB"
            sudo docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    
            echo "RUNNING DOCKER-COMPOSE"
            sudo docker-compose up --build
    
          env:
            SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            REMOTE_HOST: ${{ secrets.EC2_HOST_DNS }}
            REMOTE_USER: ${{ secrets.EC2_USERNAME }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}