-- Create Users table
CREATE TABLE Users (
  userId VARCHAR(255) NOT NULL PRIMARY KEY,
  profilePicture VARCHAR(255) NOT NULL,
  displayName VARCHAR(255) NOT NULL,
  createdAt DATETIME NOT NULL,
  lastUpdatedBy DATETIME NOT NULL
);

-- Create BlogPosts table
CREATE TABLE BlogPosts (
  blogId VARCHAR(255) NOT NULL PRIMARY KEY,
  authorId VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL,
  content VARCHAR(255) NOT NULL,
  tags TEXT[] NOT NULL,
  imageUrl VARCHAR(255) NOT NULL,
  createAt VARCHAR(255) NOT NULL,
  lastlastUpdatedBy VARCHAR(255) NOT NULL,
  publishedAt VARCHAR(255) NOT NULL,
  status ENUM('draft', 'published') NOT NULL,
  createdAt DATETIME NOT NULL,
  lastUpdatedBy DATETIME NOT NULL,
  FOREIGN KEY (authorId) REFERENCES Users(userId) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create Comments table
CREATE TABLE Comments (
  commentId VARCHAR(255) NOT NULL PRIMARY KEY,
  blogId VARCHAR(255) NOT NULL,
  userId VARCHAR(255) NOT NULL,
  content VARCHAR(255) NOT NULL,
  createAt VARCHAR(255) NOT NULL,
  lastlastUpdatedBy VARCHAR(255) NOT NULL,
  createdAt DATETIME NOT NULL,
  lastUpdatedBy DATETIME NOT NULL,
  FOREIGN KEY (blogId) REFERENCES BlogPosts(blogId) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (userId) REFERENCES Users(userId) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create Replies table
CREATE TABLE Replies (
  ReplyId VARCHAR(255) NOT NULL PRIMARY KEY,
  commentId VARCHAR(255) NOT NULL,
  userId VARCHAR(255) NOT NULL,
  content VARCHAR(255) NOT NULL,
  createAt VARCHAR(255) NOT NULL,
  lastlastUpdatedBy VARCHAR(255) NOT NULL,
  createdAt DATETIME NOT NULL,
  lastUpdatedBy DATETIME NOT NULL,
  FOREIGN KEY (commentId) REFERENCES Comments(commentId) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (userId) REFERENCES Users(userId) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create Likes table
CREATE TABLE Likes (
  likeId VARCHAR(255) NOT NULL PRIMARY KEY,
  blogId VARCHAR(255) NOT NULL,
  userId VARCHAR(255) NOT NULL,
  likeAt VARCHAR(255) NOT NULL,
  createdAt DATETIME NOT NULL,
  lastUpdatedBy DATETIME NOT NULL,
  FOREIGN KEY (blogId) REFERENCES BlogPosts(blogId) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (userId) REFERENCES Users(userId) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create CommentLikes table
CREATE TABLE CommentLikes (
  commentLikeId VARCHAR(255) NOT NULL PRIMARY KEY,
  likeId VARCHAR(255) NOT NULL,
  userId VARCHAR(255) NOT NULL,
  likeAt VARCHAR(255) NOT NULL,
  createdAt DATETIME NOT NULL,
  lastUpdatedBy DATETIME NOT NULL,
  FOREIGN KEY (likeId) REFERENCES Likes(likeId) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (userId) REFERENCES Users(userId) ON DELETE CASCADE ON UPDATE CASCADE
);
