name: CD Pipeline
run-name: Running CD Pipeline; deploying to aws ec2,and spinning up docker-compose
on: 
    workflow_run:
        workflows: ["CI Pipeline"]
        types: 
           - completed      
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY}}
          REMOTE_HOST: ${{ secrets.EC2_HOST_DNS}}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.EC2_TARGET }}
          EXCLUDE: "/dist/, /node_modules/,/.github/,/assets/,/models/"
          SCRIPT_BEFORE: |
           echo "UPDATING LINUX PACKAGES"
           sudo apt-get update -y

           cd home
           echo "REMOVE OLD DOCKER CONTAINER"
           sudo docker-compose down
           sudo docker rmi fimiz/blog -f
           sudo docker rmi nginx_container -f

           echo "GIVING EXEC PERMISSION TO fimiz.sh"
           sudo chmod +x fimiz.sh

           echo "SETTING ENVS WITH fimiz.sh"
           ./fimiz.sh

           echo "LOGIN TO DOCKERHUB"
           sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

           echo "RUNNING DOCKER-COMPOSE"
           sudo docker-compose up --build

          SCRIPT_AFTER: |
            echo $RSYNC_STDOUT