name: CD Pipeline
run-name: Running CD Pipeline; deploying to ec2
on: 
    workflow_run:
        workflows: ["CI Pipeline"]
        types: 
           - completed
          
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY}}
          REMOTE_HOST: ${{ secrets.EC2_HOST_DNS}}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.EC2_TARGET }}
          EXCLUDE: "/dist/, /node_modules/,/.github/,/assets/,/models/"
          SCRIPT_BEFORE: |
           cd home
           
           echo "Updating linux packages"
           sudo apt-get update -y

           ls

           echo "GIVING EXEC PERMISSION TO fimiz.sh"
           chmod +x fimiz.sh

           echo "SETTING ENVS WITH fimiz.sh"
           ./fimiz.sh

           echo "RUNNING DOCKER-COMPOSE"
           docker-compuse up --build

          SCRIPT_AFTER: |
            echo $RSYNC_STDOUT