name: CD Pipeline
run-name: Running CD Pipeline; deploying to ec2
on: 
    workflow_run:
        workflows: ["CI Pipeline"]
        types: 
           - completed
          
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY}}
          REMOTE_HOST: ${{ secrets.EC2_HOST_DNS}}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.EC2_TARGET }}
          EXCLUDE: "/dist/, /node_modules/,/.github/,/assets/,/models/"
          SCRIPT_BEFORE: |
           cd home
           ls -la

           echo "Updating linux packages"
           sudo apt-get update -y

          SCRIPT_AFTER: |
            echo "Giving execution permission to fimiz"
            chmod +x fimiz.sh

            echo "Setting up ENVS or running fimiz.sh"
            ./fimiz.sh

            echo "Running docker-compose"
            docker-compuse up --build
            echo $RSYNC_STDOUT