name: CI Pipeline
run-name: ${{github.author}} is running CI Pipiline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Installing dependencies
        run: npm install

      - name: Formating
        run: npm run format:fix

      - name: Checking Formart
        run: npm run format:check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Dockerhub
        env:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the blog server docker image
        run: docker build . --file Dockerfile --tag blog

      - name: Push blog server image to Dockerhub
        run: docker push fimiz/blog:latest
      
      - name: Build the blog-nginx server docker image
        run: docker build ./nginx --file Dockerfile --tag blog-nginx
      
      - name: Push blog-nginx server image to Dockerhub
        run: docker push fimiz/blog-nginx:latest

  
